export const PRODUCT_IMAGES: Record<string, any> = {
  "sandwich.png": require("../../assets/images/productimages/sandwich.png"),
  "hamburguesa.jpg": require("../../assets/images/productimages/hamburguesa.jpg"),
  "pizza.jpg": require("../../assets/images/productimages/pizza.jpg"),
  "croisant.png": require("../../assets/images/productimages/croisant.png"),
  "licuado.png": require("../../assets/images/productimages/licuado.png"),
  "frappe.png": require("../../assets/images/productimages/frappe.png"),
  "papas.jpg": require("../../assets/images/productimages/papas.jpg"),
  "galletas.jpg": require("../../assets/images/productimages/galletas.jpg"),
  "AuricularesBluetooth.png": require("../../assets/images/productimages/AudicularesBluetooth.png"),
  "SmartwatchFitPro.png": require("../../assets/images/productimages/SmartwatchFitPro.png"),
  "CargadorInalambricoRapido.png": require("../../assets/images/productimages/CargadorInalambricoRapido.png"),
  "CamperaImpermeable.png": require("../../assets/images/productimages/CamperaImpermeable.png"),
  "RemeraDeAlgodon.png": require("../../assets/images/productimages/RemeraDeAlgodon.png"),
  "SetDeSabanasPremium.png": require("../../assets/images/productimages/SetDeSabanasPremium.png"),
  "LamparaDeEscritorioLED.png": require("../../assets/images/productimages/LamparaDeEscritorioLED.png"),
  "PelotaDeFutbolN5.png": require("../../assets/images/productimages/PelotaDeFutbolN5.png"),
  "SetDeMancuernasAjustables.png": require("../../assets/images/productimages/SetDeMancuernasAjustables.png"),
};